apiVersion: natworking.k8s.io/v1
kind: NetworkPo;icy
metadata:
  name: db-policy
spec:
  podSelector:                # selecting pods to link
    matchlabels:
      role: db
  policyTypes:
  - Ingress
  - Egress
  ingress:                  # ingress - incoming traffic
  - from:
      - podSelector:
          matchLabels:
            name: api-prod
      ports:
        - protocol: TCP
          port: 3306