apiVersion: v1
kind: ReplicationController
metadata:                       # for repication controller
  name: myapp-rc
  labels:
    app: myapp
    type: fromt-end
spec:                           # for repication controller
  replicas: 3
  template:
    metadata:                   # for pod
      name: myapp-pod
      labels:
        app: myapp
    spec:                       # for repication controller
      containers:
        - name: nginx-container
          image: nginx
        - name: backend-container
          image: redis