apiVersion: apps/v1             # DIFFERENT THAN REPICATION CONTROLLER
kind: Replicaset                # DIFFERENT THAN REPICATION CONTROLLER
metadata:                       # for repication controller
  name: myapp-rc
  labels:                       # labels of repicaset itself
     app: myapp
     type: front-end
spec:                           # for repication controller
  template:
    metadata:                   # for pod
      name: myapp-pod
      labels:                   # labels defined on pod
        app: myapp
    spec:                       # for repication controller
      containers:
        - name: nginx-container
          image: nginx
        - name: backend-container
          image: redis
  replicas: 3
  selector:                     # DIFFERENT THAN REPICATION CONTROLLER, its mandatory  # match labels defined on pod to applu replicaset
    matchlabels:
      type: front-end