# limiting resources for namespaces

apiVersion: v1
kind: Resource-quota
metadata:
  name: compute-quota
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limit.cpu: "10"
    limits.memoty: 10Gi